import Link from 'next/link';
import { requireAdmin } from '@/lib/auth';
import { requireManagerTenant } from '@/lib/assessment-data';
import { createServerClient } from '@/lib/supabase';
import { displayReadiness } from '@/lib/assessment-scoring';

export default async function AssessmentsPage() {
  const user = await requireAdmin(); const tenantId = await requireManagerTenant(user); const supabase = createServerClient();
  const { data: packs } = await supabase.from('assessment_packs').select('id,title,mode,status,scenario_count,final_recommendation,created_at,candidates(name),sessions(readiness_score,candidate_ticket_text),manager_reviews(id)').eq('tenant_id',tenantId).order('created_at',{ascending:false});
  return <div className="mx-auto max-w-7xl px-6 py-10"><div className="flex items-start justify-between gap-6"><div><h1 className="text-3xl font-semibold text-white">MSP Call Readiness Assessments</h1><p className="mt-2 text-zinc-400">Put candidates and new starters through realistic support calls before they speak to real clients.</p></div><Link href="/dashboard/admin/assessments/new" className="shrink-0 rounded-lg bg-sky-300 px-5 py-2.5 font-semibold text-zinc-950">New assessment</Link></div>
    <div className="mt-8 overflow-hidden rounded-2xl border border-zinc-800"><table className="w-full text-left text-sm"><thead className="bg-zinc-900 text-zinc-400"><tr><th className="px-5 py-3">Candidate</th><th className="px-5 py-3">Progress</th><th className="px-5 py-3">Average</th><th className="px-5 py-3">Recommendation</th><th className="px-5 py-3">Status</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-zinc-800">{(packs??[]).map(pack=>{const candidate=Array.isArray(pack.candidates)?pack.candidates[0]:pack.candidates;const sessions=pack.sessions??[];const completed=sessions.filter(s=>s.candidate_ticket_text).length;const scored=sessions.filter(s=>s.readiness_score!=null);const average=scored.length?Math.round(scored.reduce((sum,s)=>sum+(s.readiness_score??0),0)/scored.length):null;return <tr key={pack.id} className="bg-zinc-950/50 text-zinc-300"><td className="px-5 py-4 font-medium text-white">{candidate?.name??pack.title}</td><td className="px-5 py-4">{completed}/3 calls</td><td className="px-5 py-4">{average==null?'—':`${average}%`}</td><td className="px-5 py-4">{displayReadiness(pack.final_recommendation)}</td><td className="px-5 py-4 capitalize">{pack.status}</td><td className="px-5 py-4 text-right"><Link href={`/dashboard/admin/assessments/${pack.id}`} className="text-sky-300 hover:text-sky-200">View</Link></td></tr>})}{!packs?.length&&<tr><td colSpan={6} className="bg-zinc-950 px-5 py-12 text-center text-zinc-500">No assessments yet.</td></tr>}</tbody></table></div>
  </div>;
}
