'use client';

import { useEffect, useState } from 'react';

type Info = { title:string; mode:string; scenario_count:number; calls_completed:number; status:string };
type Active = { session_id:string; scenario:{ title:string; issue_family:string; caller_persona?:string }; step:'call'|'ticket'; call_number:number };
type Message = { role:'candidate'|'caller'; content:string };

export function CandidateAssessment({ token }: { token: string }) {
  const [info,setInfo]=useState<Info|null>(null); const [active,setActive]=useState<Active|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [draft,setDraft]=useState(''); const [ticket,setTicket]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [complete,setComplete]=useState(false);
  useEffect(()=>{fetch(`/api/assessment/${token}`).then(async r=>{const d=await r.json(); if(!r.ok) setError(d.error); else { setInfo(d); setComplete(d.status==='completed'||d.status==='reviewed'); }});},[token]);
  async function start(){setBusy(true);setError('');const r=await fetch(`/api/assessment/${token}/start-session`,{method:'POST'});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);if(d.complete)return setComplete(true);setActive(d);}
  async function sendMessage(){if(!active||!draft.trim())return;setBusy(true);setError('');const next=[...messages,{role:'candidate' as const,content:draft.trim()}];setMessages(next);setDraft('');const r=await fetch(`/api/assessment/${token}/respond`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:active.session_id,messages:next})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setMessages([...next,{role:'caller',content:d.reply}]);}
  async function submitCall(){if(!active)return;if(messages.filter(m=>m.role==='candidate').length<3)return setError('Continue the call before ending it.');setBusy(true);setError('');const transcript=messages.map(m=>`${m.role==='candidate'?'Candidate':'Caller'}: ${m.content}`).join('\n');const r=await fetch(`/api/assessment/${token}/submit-session`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:active.session_id,transcript_text:transcript,transcript_json:messages})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setActive({...active,step:'ticket'});}
  async function submitTicket(){if(!active)return;setBusy(true);setError('');const r=await fetch(`/api/assessment/${token}/submit-ticket`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:active.session_id,candidate_ticket_text:ticket})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setMessages([]);setTicket('');setActive(null);if(d.complete)setComplete(true);else setInfo(info?{...info,calls_completed:info.calls_completed+1}:info);}
  if(error&&!info)return <main className="mx-auto max-w-2xl p-8 text-red-300">{error}</main>;
  if(!info)return <main className="p-8 text-center text-zinc-400">Loading assessment…</main>;
  if(complete)return <main className="mx-auto max-w-2xl px-6 py-20 text-center"><h1 className="text-3xl font-semibold text-white">Assessment complete</h1><p className="mt-4 text-zinc-400">Your manager will review the report.</p></main>;
  return <main className="mx-auto max-w-3xl px-6 py-12"><p className="text-sm font-medium text-sky-300">Call {active?.call_number ?? info.calls_completed+1} of {info.scenario_count}</p><h1 className="mt-2 text-3xl font-semibold text-white">MSP Call Readiness Assessment</h1><p className="mt-4 text-zinc-400">You are not expected to know every technical fix. Focus on asking clear questions, understanding business impact, communicating calmly, and capturing useful information. If you are unsure, do not guess. Explain what you would check or escalate.</p><div className="mt-4 rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-100">Do not enter passwords, secrets, or real client-confidential information.</div>
    {!active?<button onClick={start} disabled={busy} className="mt-8 rounded-lg bg-sky-300 px-5 py-3 font-semibold text-zinc-950">{busy?'Starting…':'Start next call'}</button>:<section className="mt-8 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-6"><h2 className="text-xl font-semibold text-white">{active.scenario.title}</h2><p className="mt-1 text-sm text-zinc-400">Caller: {active.scenario.caller_persona || 'MSP client'}</p>{active.step==='call'?<><div className="mt-5 min-h-72 space-y-3 rounded-lg bg-zinc-950 p-4">{messages.length===0&&<p className="text-sm text-zinc-500">Open the call as you would with a real client.</p>}{messages.map((message,index)=><div key={index} className={`max-w-[85%] rounded-lg px-4 py-3 text-sm ${message.role==='candidate'?'ml-auto bg-sky-400/15 text-sky-100':'bg-zinc-800 text-zinc-200'}`}><p className="mb-1 text-xs font-medium uppercase text-zinc-500">{message.role}</p>{message.content}</div>)}</div><div className="mt-3 flex gap-2"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();sendMessage();}}} placeholder="Speak to the caller…" className="flex-1 rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white"/><button onClick={sendMessage} disabled={busy||!draft.trim()} className="rounded-lg border border-sky-400/40 px-4 text-sky-200">Send</button></div><button onClick={submitCall} disabled={busy} className="mt-4 rounded-lg bg-sky-300 px-5 py-2.5 font-semibold text-zinc-950">{busy?'Working…':'End call and write ticket'}</button></>:<><p className="mt-5 text-sm text-zinc-300">Write the ticket another technician would need: issue, user/client, device, impact, scope, checks, priority, and next action.</p><textarea value={ticket} onChange={e=>setTicket(e.target.value)} className="mt-3 min-h-56 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3 text-white"/><button onClick={submitTicket} disabled={busy} className="mt-4 rounded-lg bg-sky-300 px-5 py-2.5 font-semibold text-zinc-950">{busy?'Submitting…':'Submit ticket'}</button></>}{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}</section>}
  </main>;
}
