'use client';
import { useRouter } from 'next/navigation';
import { useState } from 'react';

export function ReviewForm({ assessmentId }: { assessmentId: string }) {
  const router=useRouter();const[error,setError]=useState('');const[busy,setBusy]=useState(false);
  async function submit(formData:FormData){setBusy(true);setError('');const response=await fetch(`/api/assessments/${assessmentId}/review`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(formData))});const data=await response.json();setBusy(false);if(!response.ok)return setError(data.error||'Unable to save review');router.refresh();}
  return <form action={submit} className="space-y-4 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-6"><p className="text-sm text-zinc-400">Review the transcripts and tickets before seeing the AI assessment.</p><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-zinc-300">Your rating out of 10<input name="manager_rating" type="number" min="1" max="10" required className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white"/></label><label className="text-sm text-zinc-300">Your recommendation<select name="final_readiness" className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white"><option value="ready_low_risk_calls">Ready</option><option value="ready_with_supervision">Needs supervision</option><option value="not_ready">Not ready</option></select></label></div><label className="block text-sm text-zinc-300">Independent notes<textarea name="manager_notes" required className="mt-2 min-h-28 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white"/></label>{error&&<p className="text-sm text-red-300">{error}</p>}<button disabled={busy} className="rounded-lg bg-sky-300 px-5 py-2.5 font-semibold text-zinc-950 disabled:opacity-50">{busy?'Saving…':'Save review and reveal AI analysis'}</button></form>;
}

export function AiFeedbackForm({assessmentId}:{assessmentId:string}){const router=useRouter();const[error,setError]=useState('');async function submit(formData:FormData){const response=await fetch(`/api/assessments/${assessmentId}/review`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phase:'ai_feedback',...Object.fromEntries(formData)})});const data=await response.json();if(!response.ok)return setError(data.error||'Unable to save feedback');router.refresh();}return <form action={submit} className="mt-5 space-y-4 rounded-xl border border-sky-400/20 bg-sky-400/5 p-5"><h3 className="font-medium text-white">Calibrate the AI</h3><label className="block text-sm text-zinc-300">How useful and accurate was the AI analysis?<select name="ai_feedback_rating" className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white"><option value="5">5 — Very useful</option><option value="4">4 — Mostly useful</option><option value="3">3 — Mixed</option><option value="2">2 — Mostly wrong</option><option value="1">1 — Not useful</option></select></label><label className="block text-sm text-zinc-300">What did it get right or wrong?<textarea name="ai_feedback_comment" required className="mt-2 min-h-24 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white"/></label>{error&&<p className="text-sm text-red-300">{error}</p>}<button className="rounded-lg border border-sky-400/40 px-4 py-2 text-sm font-medium text-sky-200">Save AI feedback</button></form>}
