import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireAdmin } from '@/lib/auth';
import { requireManagerTenant } from '@/lib/assessment-data';
import { createServerClient } from '@/lib/supabase';
import { AiFeedbackForm, ReviewForm } from '@/components/assessments/ReviewForm';
import { displayReadiness } from '@/lib/assessment-scoring';

type Session={id:string;readiness_score:number|null;checkpoints:Record<string,{passed?:boolean;evidence?:string}|boolean>|null;ticket_score:{score?:number}|null;candidate_ticket_text:string|null;transcript_text:string|null;feedback_text:string|null;scenarios:{title:string;issue_family:string}|{title:string;issue_family:string}[]|null};

export default async function ReportPage({params}:{params:Promise<{id:string}>}){
  const user=await requireAdmin();const tenantId=await requireManagerTenant(user);const{id}=await params;const supabase=createServerClient();
  const{data:pack}=await supabase.from('assessment_packs').select('*,candidates(name,email),sessions(id,readiness_score,checkpoints,ticket_score,candidate_ticket_text,transcript_text,feedback_text,scenarios(title,issue_family)),manager_reviews(*)').eq('id',id).eq('tenant_id',tenantId).single();
  if(!pack)notFound();
  const candidate=Array.isArray(pack.candidates)?pack.candidates[0]:pack.candidates;const sessions=(pack.sessions??[])as Session[];const scored=sessions.filter(s=>s.readiness_score!=null);const average=scored.length?Math.round(scored.reduce((sum,s)=>sum+(s.readiness_score??0),0)/scored.length):0;const reviews=pack.manager_reviews??[];const latest=reviews.at?.(-1)??reviews[reviews.length-1];const revealed=Boolean(latest);
  return <div className="mx-auto max-w-5xl px-6 py-10"><Link href={`/dashboard/admin/assessments/${id}`} className="text-sm text-zinc-400 hover:text-white">← Assessment</Link><p className="mt-6 text-sm font-medium text-sky-300">First Calls assessment</p><h1 className="mt-2 text-3xl font-semibold text-white">{candidate?.name} readiness report</h1><p className="mt-3 text-zinc-400">Review the source evidence independently. AI analysis is revealed only after the manager records a rating.</p>
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><Card label="AI recommendation" value={revealed?displayReadiness(latest.ai_readiness):'Hidden pending review'}/><Card label="AI readiness" value={revealed?`${average}%`:'Hidden'}/><Card label="Calls completed" value={`${sessions.filter(s=>s.candidate_ticket_text).length}/3`}/></div>
    <section className="mt-10"><h2 className="text-xl font-semibold text-white">Call evidence</h2><div className="mt-4 space-y-5">{sessions.map((session,index)=><CallEvidence key={session.id} session={session} index={index} revealed={revealed}/>)}{!sessions.length&&<p className="text-zinc-500">No calls have been completed.</p>}</div></section>
    <section className="mt-10"><h2 className="mb-4 text-xl font-semibold text-white">Manager calibration</h2>{latest?<div><div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-6"><p className="font-semibold text-white">Manager: {displayReadiness(latest.final_readiness)} · {latest.manager_score/10}/10</p><p className="mt-2 text-sm text-zinc-300">AI: {displayReadiness(latest.ai_readiness)} · {latest.ai_score}%</p><p className="mt-2 text-sm text-zinc-400">{latest.agreed_with_ai?'Manager and AI agreed.':'Manager and AI differed.'}</p>{latest.manager_notes&&<p className="mt-3 text-sm text-zinc-300">{latest.manager_notes}</p>}</div>{latest.reviewed_ai_at?<p className="mt-4 rounded-lg border border-zinc-800 p-4 text-sm text-zinc-400">AI feedback saved: {latest.ai_feedback_rating}/5 — {latest.ai_feedback_comment}</p>:<AiFeedbackForm assessmentId={id}/>}</div>:<ReviewForm assessmentId={id}/>}</section>
  </div>;
}

function CallEvidence({session,index,revealed}:{session:Session;index:number;revealed:boolean}){const scenario=Array.isArray(session.scenarios)?session.scenarios[0]:session.scenarios;const checkpoints=Object.entries(session.checkpoints??{});return <article className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-6"><div className="flex justify-between"><h3 className="font-semibold text-white">Call {index+1}: {scenario?.title??'Scenario'}</h3>{revealed&&<p className="text-xl font-semibold text-sky-300">{session.readiness_score??'—'}%</p>}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><h4 className="text-sm font-medium text-white">Candidate ticket{revealed&&` · ${session.ticket_score?.score??'—'}%`}</h4><pre className="mt-2 whitespace-pre-wrap rounded-lg bg-zinc-950 p-4 text-xs text-zinc-400">{session.candidate_ticket_text??'No ticket submitted'}</pre></div><details open={!revealed}><summary className="cursor-pointer text-sm font-medium text-sky-300">Full transcript</summary><pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap rounded-lg bg-zinc-950 p-4 text-xs text-zinc-300">{session.transcript_text??'No transcript'}</pre></details></div>{revealed&&<><p className="mt-5 text-sm text-zinc-300">{session.feedback_text}</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{checkpoints.map(([key,value])=>{const detail=typeof value==='boolean'?{passed:value}:value;return <div key={key} className={`rounded-lg border p-3 text-sm ${detail.passed?'border-emerald-500/20 bg-emerald-500/5':'border-red-500/20 bg-red-500/5'}`}><p className="font-medium text-zinc-200">{detail.passed?'✓':'×'} {key.replaceAll('_',' ')}</p>{detail.evidence&&<p className="mt-1 text-xs text-zinc-500">{detail.evidence}</p>}</div>})}</div></>}</article>}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-5"><p className="text-xs uppercase tracking-wide text-zinc-500">{label}</p><p className="mt-2 text-xl font-semibold text-white">{value}</p></div>}
