import { FrameworkDefinition } from '../evaluator';

export const CALLUM_BASELINE_V1: FrameworkDefinition = {
  id: 'callum_baseline_v1',
  name: 'Callum Baseline',
  version: '1.0',
  type: 'baseline',
  category: 'call_quality',
  passThreshold: 60,
  weight: 1.0,
  description: 'Standard Callum assessment. 18 core binary criteria + 4 critical + exceptional service bonus.',
  standardsAlignments: ['ITIL 4 Incident Management', 'ITIL 4 Service Desk', 'HDI Call Monitoring 4.0'],
  criteria: [
    { id: 'submitted_ticket', label: 'Submitted a ticket', weight: 0, critical: true, category: 'fundamentals', checkType: 'event_check', checkTarget: 'ticket_submitted', passIf: 'pass', evidenceDescription: 'A ticket was submitted via Submit for Review' },
    { id: 'performed_triage', label: 'Performed ticket triage', weight: 0, critical: true, category: 'fundamentals', checkType: 'event_check', checkTarget: 'ticket_triage_submitted', passIf: 'pass', evidenceDescription: 'Candidate classified the ticket via the triage panel' },
    { id: 'safety', label: 'No unsafe actions', weight: 0, critical: true, category: 'fundamentals', checkType: 'action_not_performed', checkTarget: 'red_flag_triggered', passIf: 'pass', evidenceDescription: 'Candidate did not perform red-flagged actions' },
    { id: 'next_steps', label: 'Customer knows next steps', weight: 1, critical: true, category: 'fundamentals', checkType: 'ai_criteria', checkTarget: 'next_steps', passIf: 'pass', evidenceDescription: 'Candidate set clear next steps' },
    { id: 'identity_check', label: 'Confirmed caller identity', weight: 1, critical: false, category: 'call_control', checkType: 'ai_criteria', checkTarget: 'identity_check', passIf: 'pass_or_partial', evidenceDescription: 'Candidate asked who they were speaking to' },
    { id: 'company_check', label: 'Confirmed company/client', weight: 1, critical: false, category: 'call_control', checkType: 'ai_criteria', checkTarget: 'company_check', passIf: 'pass_or_partial', evidenceDescription: 'Candidate confirmed the client/company' },
    { id: 'customer_tone', label: 'Professional, respectful tone', weight: 1, critical: false, category: 'call_control', checkType: 'ai_criteria', checkTarget: 'customer_tone', passIf: 'pass_or_partial', evidenceDescription: 'Candidate maintained professional tone' },
    { id: 'customer_communication', label: 'Clear communication', weight: 1, critical: false, category: 'call_control', checkType: 'ai_criteria', checkTarget: 'customer_communication', passIf: 'pass_or_partial', evidenceDescription: 'Customer understood what was happening' },
    { id: 'issue_clarification', label: 'Clarified the exact issue', weight: 1, critical: false, category: 'diagnosis', checkType: 'ai_criteria', checkTarget: 'issue_clarification', passIf: 'pass_or_partial', evidenceDescription: 'Candidate restated the problem' },
    { id: 'started_when', label: 'Asked when it started', weight: 1, critical: false, category: 'diagnosis', checkType: 'ai_criteria', checkTarget: 'started_when', passIf: 'pass_or_partial', evidenceDescription: 'Candidate established timeline' },
    { id: 'impact', label: 'Asked about business impact', weight: 1, critical: false, category: 'diagnosis', checkType: 'ai_criteria', checkTarget: 'impact', passIf: 'pass_or_partial', evidenceDescription: 'Candidate asked how issue affects work' },
    { id: 'urgency', label: 'Asked about urgency/deadline', weight: 1, critical: false, category: 'diagnosis', checkType: 'ai_criteria', checkTarget: 'urgency', passIf: 'pass_or_partial', evidenceDescription: 'Candidate asked about deadlines' },
    { id: 'scope', label: 'Asked scope (one or many users)', weight: 1, critical: false, category: 'diagnosis', checkType: 'ai_criteria', checkTarget: 'scope', passIf: 'pass_or_partial', evidenceDescription: 'Candidate asked one or many users' },
    { id: 'error_or_status_capture', label: 'Captured error/status details', weight: 1, critical: false, category: 'diagnosis', checkType: 'ai_criteria', checkTarget: 'error_or_status_capture', passIf: 'pass_or_partial', evidenceDescription: 'Candidate captured error messages' },
    { id: 'recent_changes', label: 'Asked about recent changes', weight: 1, critical: false, category: 'diagnosis', checkType: 'ai_criteria', checkTarget: 'recent_changes', passIf: 'pass_or_partial', evidenceDescription: 'Candidate asked about recent changes' },
    { id: 'technical_discovery', label: 'Performed technical investigation', weight: 1, critical: false, category: 'resolution', checkType: 'ai_criteria', checkTarget: 'technical_discovery', passIf: 'pass_or_partial', evidenceDescription: 'Candidate used structured troubleshooting' },
    { id: 'escalation_judgement', label: 'Appropriate escalation', weight: 1, critical: false, category: 'resolution', checkType: 'ai_criteria', checkTarget: 'escalation_judgement', passIf: 'pass_or_partial', evidenceDescription: 'Candidate escalated appropriately' },
    { id: 'ticket_user_company', label: 'Ticket: user + company', weight: 1, critical: false, category: 'ticket_quality', checkType: 'ticket_field', checkTarget: 'requester', passIf: 'pass_or_partial', evidenceDescription: 'Ticket has requester name' },
    { id: 'ticket_issue_summary', label: 'Ticket: clear issue summary', weight: 1, critical: false, category: 'ticket_quality', checkType: 'ticket_field', checkTarget: 'issue', passIf: 'pass_or_partial', evidenceDescription: 'Ticket has issue summary' },
    { id: 'ticket_impact', label: 'Ticket: business impact', weight: 1, critical: false, category: 'ticket_quality', checkType: 'ticket_field', checkTarget: 'impact', passIf: 'pass_or_partial', evidenceDescription: 'Ticket documents business impact' },
    { id: 'ticket_urgency', label: 'Ticket: urgency/deadline', weight: 1, critical: false, category: 'ticket_quality', checkType: 'ticket_field', checkTarget: 'urgent', passIf: 'pass_or_partial', evidenceDescription: 'Ticket records urgency' },
    { id: 'ticket_checks_attempted', label: 'Ticket: checks attempted', weight: 1, critical: false, category: 'ticket_quality', checkType: 'ticket_field', checkTarget: 'checked', passIf: 'pass_or_partial', evidenceDescription: 'Ticket lists checks performed' },
    { id: 'ticket_next_step', label: 'Ticket: next step', weight: 1, critical: false, category: 'ticket_quality', checkType: 'ticket_field', checkTarget: 'next steps', passIf: 'pass_or_partial', evidenceDescription: 'Ticket has next step' },
  ],
};
