export interface AnalysisFixture {
  name: string;
  description: string;
  criteria: Record<string, { status: string; severity?: string; evidence?: string[]; notes?: string }>;
  redFlags: Array<{ type: string; severity?: string; evidence?: string }>;
  expectedScoreMax: number;
  expectedScoreMin: number;
  expectedReadiness: string;
  expectsCriticalGate?: boolean;
  expectsGateIds?: string[];
}

export const FIXTURES: AnalysisFixture[] = [
  {
    name: 'severe_abuse',
    description: 'Candidate tells customer to fuck off',
    criteria: {
      identity_check: { status: 'pass', severity: 'low', evidence: ['What is your name?'], notes: '' },
      company_check: { status: 'pass', severity: 'low', evidence: ['What company?'], notes: '' },
      issue_clarification: { status: 'pass', severity: 'low', evidence: ['Outlook not sending'], notes: '' },
      impact: { status: 'pass', severity: 'medium', evidence: ['Need to send documents'], notes: '' },
      urgency: { status: 'pass', severity: 'medium', evidence: ['When is deadline?'], notes: '' },
      scope: { status: 'pass', severity: 'low', evidence: ['Just you?'], notes: '' },
      technical_discovery: { status: 'fail', severity: 'high', evidence: [], notes: 'Did not check webmail' },
      error_or_status_capture: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      recent_changes: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      next_steps: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      customer_tone: { status: 'fail', severity: 'critical', evidence: [], notes: 'Swore at customer' },
      professional_conduct: { status: 'fail', severity: 'critical', evidence: ['fuck off'], notes: 'Told customer to fuck off' },
      customer_communication: { status: 'fail', severity: 'critical', evidence: [], notes: '' },
      safety: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_user_company: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_issue_summary: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_impact: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_urgency: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_checks_attempted: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_next_step: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      escalation_judgement: { status: 'fail', severity: 'high', evidence: [], notes: '' },
    },
    redFlags: [
      { type: 'severe_customer_abuse', severity: 'critical', evidence: 'Candidate told customer to fuck off' },
    ],
    expectedScoreMax: 10,
    expectedScoreMin: 0,
    expectedReadiness: 'not_ready',
    expectsCriticalGate: true,
    expectsGateIds: ['severe_customer_abuse'],
  },
  {
    name: 'unsafe_security',
    description: 'Candidate asks customer for password',
    criteria: {
      identity_check: { status: 'pass', severity: 'low', evidence: ['Name?'], notes: '' },
      company_check: { status: 'pass', severity: 'low', evidence: ['Company?'], notes: '' },
      issue_clarification: { status: 'pass', severity: 'low', evidence: ['Login issue'], notes: '' },
      impact: { status: 'pass', severity: 'medium', evidence: ['Blocked from work'], notes: '' },
      urgency: { status: 'pass', severity: 'medium', evidence: ['Need it today'], notes: '' },
      scope: { status: 'pass', severity: 'low', evidence: ['Just you?'], notes: '' },
      technical_discovery: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      error_or_status_capture: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      recent_changes: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      next_steps: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      customer_tone: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      professional_conduct: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      customer_communication: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      safety: { status: 'fail', severity: 'critical', evidence: ['Can you give me your password?'], notes: 'Asked for password' },
      ticket_user_company: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_issue_summary: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_impact: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_urgency: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_checks_attempted: { status: 'partial', severity: 'low', evidence: [], notes: '' },
      ticket_next_step: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      escalation_judgement: { status: 'fail', severity: 'high', evidence: [], notes: '' },
    },
    redFlags: [
      { type: 'unsafe_security_behaviour', severity: 'critical', evidence: 'Candidate asked customer for their password' },
    ],
    expectedScoreMax: 25,
    expectedScoreMin: 0,
    expectedReadiness: 'not_ready',
    expectsCriticalGate: true,
    expectsGateIds: ['unsafe_security_behaviour'],
  },
  {
    name: 'no_troubleshooting',
    description: 'Candidate gives generic replies, no questions, no ticket detail',
    criteria: {
      identity_check: { status: 'fail', severity: 'high', evidence: [], notes: 'Did not ask name' },
      company_check: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      issue_clarification: { status: 'partial', severity: 'medium', evidence: ['Okay I see'], notes: 'Vague' },
      impact: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      urgency: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      scope: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      technical_discovery: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      error_or_status_capture: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      recent_changes: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      next_steps: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      customer_tone: { status: 'pass', severity: 'low', evidence: ['Hello'], notes: 'Polite but useless' },
      professional_conduct: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      customer_communication: { status: 'partial', severity: 'medium', evidence: [], notes: '' },
      safety: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_user_company: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_issue_summary: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_impact: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_urgency: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_checks_attempted: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_next_step: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      escalation_judgement: { status: 'fail', severity: 'high', evidence: [], notes: '' },
    },
    redFlags: [
      { type: 'no_troubleshooting', severity: 'high', evidence: 'Candidate asked no meaningful questions' },
    ],
    expectedScoreMax: 40,
    expectedScoreMin: 0,
    expectedReadiness: 'not_ready',
    expectsGateIds: ['no_troubleshooting'],
  },
  {
    name: 'good_imperfect',
    description: 'Good but imperfect first-line call — misses urgency, decent ticket',
    criteria: {
      identity_check: { status: 'pass', severity: 'low', evidence: ['Can I take your name?'], notes: '' },
      company_check: { status: 'pass', severity: 'low', evidence: ['What company?'], notes: '' },
      issue_clarification: { status: 'pass', severity: 'low', evidence: ['Tell me about the issue'], notes: '' },
      impact: { status: 'pass', severity: 'medium', evidence: ['What work is blocked?'], notes: '' },
      urgency: { status: 'fail', severity: 'high', evidence: [], notes: 'Did not ask deadline' },
      scope: { status: 'pass', severity: 'low', evidence: ['Just you affected?'], notes: '' },
      technical_discovery: { status: 'pass', severity: 'low', evidence: ['Does webmail work?'], notes: '' },
      error_or_status_capture: { status: 'pass', severity: 'low', evidence: ['Any error message?'], notes: '' },
      recent_changes: { status: 'fail', severity: 'medium', evidence: [], notes: '' },
      next_steps: { status: 'pass', severity: 'low', evidence: ['Ill check and get back to you'], notes: '' },
      customer_tone: { status: 'pass', severity: 'low', evidence: ['I understand'], notes: '' },
      professional_conduct: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      customer_communication: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      safety: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_user_company: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_issue_summary: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_impact: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_urgency: { status: 'fail', severity: 'high', evidence: [], notes: 'Missing from ticket' },
      ticket_checks_attempted: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_next_step: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      escalation_judgement: { status: 'pass', severity: 'low', evidence: [], notes: '' },
    },
    redFlags: [],
    expectedScoreMin: 65,
    expectedScoreMax: 90,
    expectedReadiness: 'ready',
  },
  {
    name: 'perfect_call',
    description: 'Perfect candidate — all checks pass, no red flags',
    criteria: (() => {
      const c: any = {};
      const keys = ['identity_check','company_check','issue_clarification','started_when','impact','urgency','scope','technical_discovery','error_or_status_capture','recent_changes','next_steps','customer_tone','professional_conduct','customer_communication','safety','ticket_user_company','ticket_issue_summary','ticket_impact','ticket_urgency','ticket_checks_attempted','ticket_next_step','escalation_judgement'];
      for (const k of keys) c[k] = { status: 'pass', severity: 'low', evidence: ['Did it'], notes: '' };
      return c;
    })(),
    redFlags: [],
    expectedScoreMin: 85,
    expectedScoreMax: 100,
    expectedReadiness: 'ready',
  },
  {
    name: 'hallucinated_fix',
    description: 'Candidate claims issue is fixed without evidence',
    criteria: {
      identity_check: { status: 'pass', severity: 'low', evidence: ['Name?'], notes: '' },
      company_check: { status: 'pass', severity: 'low', evidence: ['Company?'], notes: '' },
      issue_clarification: { status: 'partial', severity: 'medium', evidence: ['Outlook issue'], notes: 'Vague' },
      impact: { status: 'pass', severity: 'medium', evidence: ['Blocked?'], notes: '' },
      urgency: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      scope: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      technical_discovery: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      error_or_status_capture: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      recent_changes: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      next_steps: { status: 'pass', severity: 'low', evidence: ['I fixed it'], notes: '' },
      customer_tone: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      professional_conduct: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      customer_communication: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      safety: { status: 'partial', severity: 'medium', evidence: [], notes: '' },
      ticket_user_company: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_issue_summary: { status: 'pass', severity: 'low', evidence: [], notes: '' },
      ticket_impact: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_urgency: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_checks_attempted: { status: 'fail', severity: 'high', evidence: [], notes: '' },
      ticket_next_step: { status: 'pass', severity: 'low', evidence: ['Resolved'], notes: '' },
      escalation_judgement: { status: 'fail', severity: 'high', evidence: [], notes: '' },
    },
    redFlags: [
      { type: 'hallucinated_fix', severity: 'high', evidence: 'Candidate claimed fix without evidence' },
    ],
    expectedScoreMax: 50,
    expectedScoreMin: 0,
    expectedReadiness: 'not_ready',
    expectsGateIds: ['hallucinated_fix'],
  },
  {
    name: 'no_ticket',
    description: 'Missing ticket — should not be analysed',
    criteria: {},
    redFlags: [],
    expectedScoreMax: 0,
    expectedScoreMin: 0,
    expectedReadiness: 'not_ready',
  },
];
