import { SimPack, SimPackScoringCriterion, SimState } from '../types';
import { ScoringEvent } from '../scoring';

export const PASSWORD_RESET_PACK_ID = 'pack-password-reset-v1';

const getInitialState = (): SimState => ({
  phase: 'not_started',
  call: { startedAt: null, endedAt: null, customerMood: 'frustrated', factsRevealed: [] },
  remote: { connected: false, deviceName: 'DESKTOP-WIN-2H5', currentApp: 'none' },
  toolStates: {},
  evidence: { askedImpact: false, askedScope: false, confirmedUser: false, confirmedDevice: false, checkedObviousCause: false, verifiedFix: false },
  flags: { guessedWithoutEvidence: false, performedRiskyAction: false, ignoredUserEmotion: false },
  discovered: [],
});

const criteriaList: SimPackScoringCriterion[] = [
  { id: 'confirmed_user', label: 'Verified caller identity', category: 'call_control', weight: 10, mandatory: true, check: 'tag_present', target: 'communication.user_confirmation', positive: true, description: 'Candidate confirmed the caller name or employee ID before proceeding', gradingGuide: 'Look for "can I confirm your name?" or "what is your employee ID?"' },
  { id: 'identified_account', label: 'Identified the account/service locked', category: 'diagnosis', weight: 8, mandatory: false, check: 'fact_revealed', target: 'Account is locked', positive: true, description: 'Candidate identified which account or service is locked', gradingGuide: 'Look for questions about which system they need access to' },
  { id: 'asked_impact', label: 'Asked business impact', category: 'call_control', weight: 8, mandatory: false, check: 'tag_present', target: 'communication.impact_question', positive: true, description: 'Candidate asked what work is blocked', gradingGuide: 'Look for "what do you need to access?" or "is this blocking your work?"' },
  { id: 'asked_scope', label: 'Asked scope', category: 'call_control', weight: 5, mandatory: false, check: 'tag_present', target: 'communication.scope_question', positive: true, description: 'Candidate asked whether others are also affected', gradingGuide: 'Look for "is anyone else having this issue?"' },
  { id: 'set_expectations', label: 'Set clear expectations', category: 'call_control', weight: 8, mandatory: false, check: 'tag_present', target: 'communication.empathy', positive: true, description: 'Candidate set expectations on resolution time', gradingGuide: 'Look for timeframe or next-steps communication' },
  { id: 'verified_identity_safely', label: 'Verified identity without asking for password', category: 'professionalism', weight: 15, mandatory: true, check: 'state_value', target: 'flags.performedRiskyAction', positive: true, value: false, description: 'Candidate did not ask for the caller password or MFA code', gradingGuide: 'Critical security check. Must NOT ask for password/MFA.' },
  { id: 'used_secure_reset', label: 'Used secure password reset process', category: 'resolution', weight: 10, mandatory: true, check: 'tag_present', target: 'verification.user_confirmed', positive: true, description: 'Candidate initiated password reset through proper channels', gradingGuide: 'Look for "I will send you a reset link" or "I will initiate a password reset from here"' },
  { id: 'confirmed_fix_works', label: 'Confirmed the fix works', category: 'resolution', weight: 10, mandatory: false, check: 'state_value', target: 'evidence.verifiedFix', positive: true, value: true, description: 'Candidate confirmed the user can log in after reset', gradingGuide: 'Look for "can you try logging in now?" or similar verification' },
  { id: 'ticket_details', label: 'Ticket has all required fields', category: 'ticket_quality', weight: 8, mandatory: false, check: 'tag_present', target: 'ticket.root_cause_present', positive: true, description: 'Ticket includes user, issue, resolution, and next steps', gradingGuide: 'Required fields: user, issue, account, resolution, next_step' },
  { id: 'avoided_security_risk', label: 'Avoided security risks', category: 'professionalism', weight: 10, mandatory: true, check: 'state_value', target: 'flags.guessedWithoutEvidence', positive: true, value: false, description: 'Candidate did not suggest unsafe workarounds', gradingGuide: 'No risky suggestions like sharing temporary passwords over chat' },
  { id: 'ticket_impact', label: 'Impact documented in ticket', category: 'ticket_quality', weight: 5, mandatory: false, check: 'tag_present', target: 'ticket.impact_noted', positive: true, description: 'Business impact noted in ticket', gradingGuide: 'Ticket describes what work is blocked' },
  { id: 'ticket_next_step', label: 'Next steps in ticket', category: 'ticket_quality', weight: 5, mandatory: false, check: 'tag_present', target: 'ticket.next_step_set', positive: true, description: 'Ticket includes next action or escalation plan', gradingGuide: 'Ticket has follow-up action set' },
];

export function getPasswordResetPack(): SimPack {
  return {
    id: PASSWORD_RESET_PACK_ID,
    version: '1.0',
    title: 'Password Reset / Account Lockout',
    description: 'Caller cannot log into their account after multiple failed attempts. Tests security awareness, identity verification, and proper escalation.',
    level: 1,
    severity: 'P3',
    category: 'identity',
    queueTitle: 'Account locked — urgent access needed',
    requesterName: 'James Wilson',
    company: 'Alder & Co Legal',
    department: 'Paralegal',
    location: 'Floor 3, City Office',
    mode: 'call_only',
    taxonomyItemId: 'identity.access_management',

    customer: {
      name: 'James',
      company: 'Alder & Co Legal',
      role: 'Paralegal',
      temperament: 'stressed',
      openingLine: 'Hi, I think my account is locked or something. I\'ve been trying to log in for the past 20 minutes and it keeps saying "invalid credentials". I\'ve got a deadline in an hour.',
      subject: 'Account locked — urgent access needed',
      gender: 'male',
      azureVoice: {
        neutral: { voiceName: 'en-GB-SoniaNeural', style: 'worried', styleDegree: 0.7, rate: '+10%', pitch: '+5%' },
        frustrated: { voiceName: 'en-GB-SoniaNeural', style: 'angry', styleDegree: 1, rate: '+15%', pitch: '+8%' },
        reassured: { voiceName: 'en-GB-SoniaNeural', style: 'relieved', styleDegree: 0.6, rate: '-5%', pitch: '-2%' },
      },
    },

    callerBehavior: {
      archetype: 'direct',
      defaultIntensity: 2,
      frustrationTriggers: ['being asked the same question twice', 'being told to wait without explanation'],
      reassuranceTriggers: ['clear next steps', 'quick acknowledgement of urgency'],
      curveballProbability: 0.2,
      preferredCurveballs: ['this happened last week too', 'I really need this done now'],
      verbosity: 'normal',
      technicalLevel: 'somewhat_technical',
      initialMood: 'frustrated',
    },

    initialState: getInitialState(),

    hiddenTruth: {
      rootCause: 'Account locked due to multiple failed login attempts after forgotten password',
      correctFix: 'Verify identity through HR records, initiate password reset from admin console, send reset link to personal email',
      idealDiagnosticPath: [
        'Confirm caller identity (name, department, manager)',
        'Identify which account is locked',
        'Check lockout status in admin console',
        'Verify identity through secondary method (personal email, manager approval)',
        'Initiate password reset',
        'Send reset link via personal email',
        'Confirm user can log in',
        'Document in ticket',
      ],
      factsOnlyRevealAfter: {
        'asked_which_account': ['It\'s my main login — the one for email and documents. I think it\'s the same one for everything.'],
        'asked_recent_changes': ['I changed my password last week actually. Maybe that\'s related?'],
        'asked_impact_detail': ['I have court documents that need to be filed by 4pm. If I can\'t get in, my boss will have to do it.'],
      },
    },

    tools: ['customer_chat', 'ticket', 'notes'],
    actions: [
      {
        id: 'start_call',
        tool: 'customer_chat',
        label: 'Start call',
        allowedPhases: ['not_started'],
        transitionsTo: 'call_active',
        observation: 'Call connected. Customer is on the line.',
        scoreImpact: { positive: ['call_control'] },
      },
      {
        id: 'end_call',
        tool: 'customer_chat',
        label: 'End call',
        allowedPhases: ['call_active'],
        transitionsTo: 'ticketing',
        effects: { 'call.endedAt': '$now' as any },
        observation: 'Call ended. Proceed to write your ticket.',
        scoreImpact: { positive: ['call_control'] },
      },
      {
        id: 'verify_identity',
        tool: 'customer_chat',
        label: 'Verify caller identity',
        allowedPhases: ['call_active'],
        observation: 'Customer confirms their name and department. You can proceed with the verification process.',
        taxonomyTags: ['communication.user_confirmation'],
        scoreImpact: { positive: ['call_control'] },
      },
      {
        id: 'ask_which_account',
        tool: 'customer_chat',
        label: 'Ask which account is locked',
        allowedPhases: ['call_active'],
        observation: 'Customer: "It\'s my main login — the one for email and documents."',
        revealsFacts: ['Account is locked'],
        taxonomyTags: ['diagnostic.application_state_checked'],
        scoreImpact: { positive: ['diagnosis'] },
      },
      {
        id: 'ask_impact',
        tool: 'customer_chat',
        label: 'Ask business impact',
        allowedPhases: ['call_active'],
        observation: 'Customer explains the urgency and deadline.',
        taxonomyTags: ['communication.impact_question'],
        scoreImpact: { positive: ['call_control'] },
      },
      {
        id: 'ask_recent_changes',
        tool: 'customer_chat',
        label: 'Ask about recent changes',
        allowedPhases: ['call_active'],
        observation: 'Customer mentions they changed their password last week.',
        taxonomyTags: ['diagnostic.application_state_checked'],
        scoreImpact: { positive: ['diagnosis'] },
      },
      {
        id: 'initiate_reset',
        tool: 'customer_chat',
        label: 'Initiate password reset',
        allowedPhases: ['call_active'],
        effects: { 'toolStates.resetInitiated': true },
        observation: 'Password reset initiated. Sending reset link to personal email on file.',
        taxonomyTags: ['verification.user_confirmed'],
        scoreImpact: { positive: ['resolution'] },
      },
      {
        id: 'confirm_reset_works',
        tool: 'customer_chat',
        label: 'Confirm reset worked',
        allowedPhases: ['call_active'],
        effects: { 'evidence.verifiedFix': true, 'toolStates.resetConfirmed': true },
        observation: 'Customer confirms they received the email and can log in successfully.',
        revealsFacts: ['Fix verified'],
        taxonomyTags: ['verification.user_confirmed'],
        scoreImpact: { positive: ['resolution', 'verification'] },
      },
      /* ── Red flag actions ── */
      {
        id: 'ask_for_password',
        tool: 'customer_chat',
        label: 'Ask customer for their password',
        allowedPhases: ['call_active'],
        observation: 'This is a security risk. Never ask for passwords.',
        redFlag: {
          id: 'unsafe_security_behaviour',
          severity: 'critical',
          message: 'Candidate asked the customer for their password — severe security risk.',
        },
        effects: { 'flags.performedRiskyAction': true },
        taxonomyTags: ['red_flag.destructive_action_without_evidence'],
        scoreImpact: { negative: ['professionalism'] },
      },
      {
        id: 'share_temp_password',
        tool: 'customer_chat',
        label: 'Share temporary password in chat',
        allowedPhases: ['call_active'],
        observation: 'Sending passwords over chat is a security risk. Use the proper reset process.',
        redFlag: {
          id: 'unsafe_security_behaviour',
          severity: 'critical',
          message: 'Candidate shared a password over chat — severe security risk.',
        },
        effects: { 'flags.guessedWithoutEvidence': true },
        taxonomyTags: ['red_flag.destructive_action_without_evidence'],
        scoreImpact: { negative: ['professionalism'] },
      },
      {
        id: 'escalate_without_trying',
        tool: 'customer_chat',
        label: 'Escalate to Tier 2 without trying reset',
        allowedPhases: ['call_active'],
        observation: 'Escalation is premature. A password reset can be handled at tier 1.',
        redFlag: {
          id: 'escalate_without_basic_checks',
          severity: 'major',
          message: 'Candidate escalated without attempting a basic password reset.',
        },
        taxonomyTags: ['red_flag.escalate_without_basic_checks'],
        scoreImpact: { negative: ['diagnosis'] },
      },
    ],

    cmdCommands: [],

    scoringDefaults: {
      categoryWeights: { call_control: 30, diagnosis: 15, resolution: 20, ticket_quality: 15, professionalism: 20 },
      criteria: criteriaList,
      mandatoryCheckpoints: ['confirmed_user', 'verified_identity_safely', 'used_secure_reset', 'avoided_security_risk'],
      redFlags: [
        { id: 'unsafe_security_behaviour', severity: 'critical', message: 'Unsafe security behaviour — password or MFA compromise' },
        { id: 'escalate_without_basic_checks', severity: 'major', message: 'Escalated without basic checks' },
      ],
      diagnosticChecklist: [
        { id: 'confirmed_user', label: 'Verified caller identity', criteria: 'confirmed_user' },
        { id: 'identified_account', label: 'Identified the locked account', criteria: 'identified_account' },
        { id: 'asked_impact', label: 'Asked business impact', criteria: 'asked_impact' },
        { id: 'used_secure_reset', label: 'Used secure password reset process', criteria: 'used_secure_reset' },
        { id: 'confirmed_fix_works', label: 'Confirmed fix works', criteria: 'confirmed_fix_works' },
        { id: 'avoided_security_risk', label: 'Avoided security risks', criteria: 'avoided_security_risk' },
        { id: 'ticket_details', label: 'Ticket has required details', criteria: 'ticket_details' },
      ],
      failGates: [
        { id: 'unsafe_security', label: 'Unsafe security behaviour', severity: 'critical', scoreCap: 10, overrideReadiness: 'not_ready', redFlagType: 'unsafe_security_behaviour' },
        { id: 'escalate_without_checks', label: 'Escalated without basic checks', severity: 'major', scoreCap: 50, redFlagType: 'escalate_without_basic_checks' },
      ],
      derivedGates: [],
      thresholds: { ready: 80, needs_supervision: 60 },
      idealTicket: {
        summary: 'Password reset for James Wilson (Paralegal, Alder & Co Legal) after account lockout',
        requiredFields: ['user', 'company', 'account', 'issue_summary', 'impact', 'resolution', 'verification', 'next_step'],
        mustMention: ['James Wilson', 'Alder & Co Legal', 'password reset', 'account lockout', 'identity verified', 'reset link sent'],
        mustNotInvent: ['password shared in chat', 'bypassed identity verification', 'unauthorized access granted'],
      },
    },

    rubric: {
      call_control: { weight: 3, label: 'Call control and verification' },
      diagnosis: { weight: 2, label: 'Issue identification' },
      resolution: { weight: 2, label: 'Password reset process' },
      ticket_quality: { weight: 2, label: 'Ticket documentation' },
      professionalism: { weight: 3, label: 'Security and professionalism' },
    },
    redFlags: [
      { id: 'unsafe_security_behaviour', severity: 'critical', message: 'Unsafe security behaviour — password or MFA compromise' },
      { id: 'escalate_without_basic_checks', severity: 'major', message: 'Escalated without basic checks' },
    ],
    idealTicket: {
      summary: 'Password reset for James Wilson (Paralegal, Alder & Co Legal) after account lockout',
      requiredFields: ['user', 'company', 'account', 'issue_summary', 'impact', 'resolution', 'verification', 'next_step'],
      mustMention: ['James Wilson', 'Alder & Co Legal', 'password reset', 'account lockout', 'identity verified', 'reset link sent'],
      mustNotInvent: ['password shared in chat', 'bypassed identity verification', 'unauthorized access granted'],
    },
    scoringCriteria: criteriaList,
    diagnosticChecklist: [
      { id: 'confirmed_user', label: 'Verified caller identity', criteria: 'confirmed_user' },
      { id: 'identified_account', label: 'Identified the locked account', criteria: 'identified_account' },
      { id: 'asked_impact', label: 'Asked business impact', criteria: 'asked_impact' },
      { id: 'used_secure_reset', label: 'Used secure password reset process', criteria: 'used_secure_reset' },
      { id: 'confirmed_fix_works', label: 'Confirmed fix works', criteria: 'confirmed_fix_works' },
      { id: 'avoided_security_risk', label: 'Avoided security risks', criteria: 'avoided_security_risk' },
      { id: 'ticket_details', label: 'Ticket has required details', criteria: 'ticket_details' },
    ],
    managerReviewHints: {
      keyCriteria: ['confirmed_user', 'verified_identity_safely', 'used_secure_reset', 'confirmed_fix_works'],
      commonMistakes: ['Asks for the customer password', 'Shares a temporary password in chat', 'Does not verify identity before making changes', 'Escalates prematurely'],
      whatGoodLooksLike: 'Identity verified via employee records, password reset initiated through proper admin console, reset link sent to personal email, user confirms they can log in.',
      calibrationNotes: 'Security awareness is the primary skill being tested. Did they ask "what is your password?" (fail) or "let me verify your identity — what is your employee ID?" (pass). The identity verification method matters more than speed.',
    },
    taxonomyClassification: ['identity.access_management', 'identity.password_reset', 'diagnostic.scope_isolation'],
  };
}
